# Generated by Django 4.1.7 on 2023-03-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0004_feedback_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=200)),
                ('price', models.IntegerField(default=False)),
                ('image', models.CharField(default='', max_length=20)),
                ('is_available', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='Expert',
            new_name='Restaurant',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='expert',
            new_name='restaurant',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='expert',
            new_name='restaurant',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='expert',
            new_name='restaurant',
        ),
        migrations.DeleteModel(
            name='Expertise',
        ),
    ]
