# Generated by Django 4.1.7 on 2023-03-04 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0011_alter_payment_charges'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='pay_mode',
            new_name='payMode',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='pay_status',
            new_name='payStatus',
        ),
    ]
