# Generated by Django 4.1.7 on 2023-03-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0012_rename_pay_mode_payment_paymode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='test',
            field=models.IntegerField(default=False),
        ),
    ]
